version: '3.8'

services:
  app:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - "80:80"
    command: sh -c "npm install && npx ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run -d src/data-source.ts && npx nodemon --legacy-watch src/index.ts"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Mapeamento da porta
    volumes:
      - pg-data:/var/lib/postgresql/data  # Apenas volume de dados, sem pg_hba.conf

volumes:
  pg-data:
